### PR TITLE
switch to new abseil builds 

### LINKED ISSUE #28: Roll back abseil migration once new conda-forge-pinnings are in place
### Comment:

xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3159

### PR DESCRIPTION
**Pull request by h-vetinari**
Towards https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3399

Closes: https://github.com/conda-forge/obake-feedstock/issues/28

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin please rerender

**Comment by h-vetinari** [comment]
Aha. This is a C++20 library, and compiling with C++17 breaks the build. However, this just restarts the discussion from https://github.com/conda-forge/abseil-cpp-feedstock/issues/45, but now with C++20 vs. C++17

**Comment by hmaarrfk** [comment]
is it true to say that C++20 was never compiled for abseil? yet this library still "functioned" and was likely not hitting the problematic edge cases?

**Comment by bluescarni** [comment]
@h-vetinari @hmaarrfk I don't think this has anything to do with the C++ standard, the build failures are due to the ``fmt`` library removing certain APIs in recent versions. #31 fails for the same reasons.

I never noticed anything weird while mixing C++20 code with abseil, but I have been careful about using the least amount possible of code from abseil (fundamentally I care only about the swiss hash containers).

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
Thank you for being so explicit in your usage.

Reading on the ABSEIL documentation, it seems that those maps aren't exposing and stdlib symbols since they are complimentary to the provided maps.

**Pull request merged**
