### PR TITLE
Try some improvements to the recipe.

### PR DESCRIPTION
**Pull request by bluescarni**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bluescarni** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
@conda-forge-admin, please rerender

**Comment by bluescarni** [comment]
@isuruf is the usage of ``ignore_run_exports`` correct here?

Basically, ``tbb-devel`` is needed as a ``host`` dependency, but the produced library does not employ any symbol from ``libtbb.so`` (because the TBB usage in the obake source code is limited to the header-only parts). Thus, ``libobake.so`` does not need the runtime dependency on ``tbb`` implied by ``tbb-devel``'s ``run_exports``.

Is this reasoning correct?

**Comment by isuruf** [comment]
> Is this reasoning correct?

Yes

**Pull request merged**
